# Generated by Django 4.0.4 on 2022-06-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=516)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('A', 'Auteur'), ('M', 'Membre')], default='M', max_length=1)),
                ('permission', models.CharField(choices=[('C', 'Créer'), ('R', 'Lire'), ('CR', 'Créer et Lire'), ('CRUD', 'Créer, Lire, Actualiser, Supprimer')], default='C', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48)),
                ('description', models.CharField(max_length=516)),
                ('tag', models.CharField(choices=[('B', 'Bug'), ('I', 'Amélioration'), ('T', 'Tâche')], default='T', max_length=1)),
                ('priority', models.CharField(choices=[('1', 'Faible'), ('2', 'Moyenne'), ('3', 'Elevé')], default='1', max_length=1)),
                ('status', models.CharField(choices=[('1', 'À faire'), ('2', 'En cours'), ('3', 'Terminé')], default='1', max_length=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48)),
                ('description', models.CharField(max_length=516)),
                ('type', models.CharField(choices=[('B', 'Back-end'), ('F', 'Front-end'), ('I', 'IOS'), ('A', 'Android')], default='F', max_length=1)),
            ],
        ),
    ]
