# Generated by Django 4.0.4 on 2022-05-19 13:50

import api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('C', 'Créer'), ('R', 'Lire'), ('U', 'Actualiser'), ('D', 'Supprimer')], default='R', max_length=1)),
                ('role', models.CharField(choices=[('R', 'Responsable'), ('M', 'Membre')], default='M', max_length=12)),
                ('contributor', models.ForeignKey(on_delete=models.SET(api.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48)),
                ('description', models.CharField(max_length=516)),
                ('type', models.CharField(choices=[('B', 'Back-end'), ('F', 'Front-end'), ('I', 'IOS'), ('A', 'Android')], default='F', max_length=1)),
                ('author_user', models.ForeignKey(on_delete=models.SET(api.models.get_sentinel_user), to='api.contributor')),
            ],
        ),
    ]
