# Generated by Django 4.0.4 on 2022-05-19 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='contributor',
            new_name='user',
        ),
    ]
