# Generated by Django 4.0.4 on 2022-05-19 15:19

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_contributor_contributor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=48)),
                ('description', models.CharField(max_length=516)),
                ('tag', models.CharField(choices=[('B', 'Bug'), ('I', 'Amélioration'), ('T', 'Tâche')], default='T', max_length=1)),
                ('priority', models.CharField(choices=[('1', 'Faible'), ('2', 'Moyenne'), ('3', 'Elevé')], default='1', max_length=1)),
                ('status', models.CharField(choices=[('1', 'À faire'), ('2', 'En cours'), ('3', 'Terminé')], default='1', max_length=1)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('assignee_user', models.ForeignKey(on_delete=models.SET(api.models.get_sentinel_user), related_name='issue_assignee', to='api.contributor')),
                ('author_user', models.ForeignKey(on_delete=models.SET(api.models.get_sentinel_user), related_name='issue_author', to='api.contributor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=516)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('author_user', models.ForeignKey(on_delete=models.SET(api.models.get_sentinel_user), related_name='comment_author', to='api.contributor')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.issue')),
            ],
        ),
    ]
