# Generated by Django 4.0.4 on 2022-05-19 16:58

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_issue_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='author_user',
        ),
        migrations.AddField(
            model_name='contributor',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='author_users',
            field=models.ManyToManyField(through='api.Contributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_user',
            field=models.ForeignKey(on_delete=models.SET(api.models.get_sentinel_user), related_name='comment_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('O', 'Responsable'), ('A', 'Auteur'), ('M', 'Membre')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assignee_user',
            field=models.ForeignKey(on_delete=models.SET(api.models.get_sentinel_user), related_name='issue_assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='author_user',
            field=models.ForeignKey(on_delete=models.SET(api.models.get_sentinel_user), related_name='issue_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
