# Generated by Django 4.0.4 on 2022-05-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_project_author_user_contributor_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='permission',
            field=models.CharField(choices=[('C', 'Créer'), ('R', 'Lire'), ('CR', 'Créer et Lire'), ('CRUD', 'Créer, Lire, Actualiser, Supprimer')], default='C', max_length=4),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('A', 'Auteur'), ('M', 'Membre')], default='M', max_length=1),
        ),
    ]
