# Generated by Django 4.0.4 on 2022-05-24 08:39

import api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_alter_contributor_permission_alter_contributor_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(through='api.Contributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='project',
            name='author_users',
        ),
        migrations.AddField(
            model_name='project',
            name='author_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(api.models.get_sentinel_user), related_name='project_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
